---
title: "phyloseq analysis for blue-jam project: family level, 2nd sequencing run"
author: "jen nguyen"
date of last update: "10/25/2021"
output: html_document
---

Questions:
   
1. Which taxa consistently change in abundance between mucus and tissue samples? Mucus and lumen?
2. Are any taxa only present in tissue samples? Only mucus? Only lumen?



```{r initialize, include=FALSE}
library(ggplot2)
library(here)
library(phyloseq)
library(Biostrings)
library(tidyverse)
theme_set(theme_bw())
```

```{r read sample metadata into data frame}
meta <- read_csv(here("data","meta","sample_metadata_oct14.csv"),
                      col_types = cols(
                        Name = col_character(),
                        Extraction = col_date(format = ""),
                        Mouse = col_character(),
                        Replicate = col_character(),
                        Location = col_character()#,
                        #Pair = col_double()
                      ))
df <- meta %>% column_to_rownames("Name")
```

```{r add "pair" variable to dataframe}
Pair <- c(1,1,1,2,2,2,3,3,3,4,4,5,5,6,6,7,7,NA,NA,NA)
df <- mutate(df,Pair)
```

```{r load dada2 outputs specific to Oct 14 data}
seqtab <- readRDS(here("output","dada2_20211014","seqtable_oct14.rds")) # raw sequence table
seqtab.nochim <- readRDS(here("output","dada2_20211014","seqtable_nochimeras_oct14.rds")) 
taxa <- readRDS(here("output","dada2_20211014","taxonomic_assignments_oct14.rds")) # taxonomic assignments
```

```{r construct phyloseq object from dada2 output}
ps <- phyloseq(otu_table(seqtab.nochim, taxa_are_rows=FALSE), 
               sample_data(df), 
               tax_table(taxa))
```

```{r ASV short names}
dna <- Biostrings::DNAStringSet(taxa_names(ps))
names(dna) <- taxa_names(ps)
ps <- merge_phyloseq(ps, dna)
taxa_names(ps) <- paste0("ASV", seq(ntaxa(ps)))
ps
```

```{r melt ps object into dataframe}
df <- ps %>%
  tax_glom("Family") %>%
  psmelt %>%
  with_groups(Sample, mutate, Proportion = Abundance / sum(Abundance))
#  group_by(Sample) %>%
#  mutate(Proportion = Abundance / sum(Abundance)) %>%
#  ungroup
```

```{r 1.0 mucus vs tissue, all pairs}
df %>%
  filter(Location %in% c('Mucus', 'Tissue')) %>%
  ggplot(aes(Location, Proportion, color = Family)) +
  geom_point() +
  geom_line(aes(group = Pair)) +
  facet_wrap(~Family, scales = 'free_y') +
  theme(legend.position = 'none')
```

```{r 1.1 lumen vs mucus, all pairs}
df %>%
  filter(Location %in% c('Luminal', 'Mucus')) %>%
  ggplot(aes(Location, Proportion, color = Family)) +
  geom_point() +
  geom_line(aes(group = Pair)) +
  facet_wrap(~Family, scales = 'free_y') +
  theme(legend.position = 'none')
```

```{r 1.3 lumen vs mucus vs tissue}
df %>%
  filter(Location %in% c('Luminal', 'Mucus', 'Tissue')) %>%
  ggplot(aes(Location, Proportion, color = Family)) +
  geom_point() +
  geom_line(aes(group = Pair)) +
  facet_wrap(~Family, scales = 'free_y') +
  theme(legend.position = 'none')
```

```{r 1.4 isolate families with interesting signal}
df %>% 
  filter(Family %in% c('Acholeplasmataceae','Akkermansiaceae','Barnesiellaceae','Lachnospiraceae','Lactobacillaceae','Muribaculaceae')) %>%
  filter(Location %in% c('Luminal', 'Mucus', 'Tissue')) %>%
  ggplot(aes(Location, Proportion, color = Family)) +
  geom_point() +
  geom_line(aes(group = Pair)) +
  facet_wrap(~Family, scales = 'free_y') +
  theme(legend.position = 'none') +
  ggtitle("Selected families, 2nd seq")
```




# basic overview of dataset
```{r 0.1 bacterial families by location}
df %>%
  filter(Location %in% c('Luminal', 'Mucus', 'Tissue')) %>%
  ggplot(aes(x=Sample, y=Proportion, fill= Family)) + 
  geom_col() + facet_wrap(~Location, scales = 'free_x')
```

```{r 0.2 bacterial families in controls}
df %>%
  filter(Sample %in% c('Jen18', 'mock2', 'NTC2')) %>%
  ggplot(aes(x=Sample, y=Proportion, fill= Family)) + 
  geom_col() + facet_wrap(~Mouse, scales = 'free_x') +
  theme(legend.position = 'none')
```


```{r 0.3 read counts across samples}
df %>%
  ggplot(aes(x=Sample, y=Abundance, fill= Family)) + 
  geom_col() + facet_wrap(~Mouse,scales = 'free_x') +
  theme(legend.position = 'none')
```


```{r}
sessionInfo()
```

